name: DL1
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - blosc=1.21.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - cffi=1.15.1
  - cfitsio=3.470
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - cloudpickle=2.0.0
  - contourpy=1.0.5
  - cryptography=38.0.4
  - cuda=11.7.1
  - cuda-cccl=11.7.91
  - cuda-command-line-tools=11.7.1
  - cuda-compiler=11.7.1
  - cuda-cudart=11.7.99
  - cuda-cudart-dev=11.7.99
  - cuda-cuobjdump=11.7.91
  - cuda-cupti=11.7.101
  - cuda-cuxxfilt=11.7.91
  - cuda-demo-suite=12.0.76
  - cuda-documentation=12.0.76
  - cuda-driver-dev=11.7.99
  - cuda-gdb=12.0.90
  - cuda-libraries=11.7.1
  - cuda-libraries-dev=11.7.1
  - cuda-memcheck=11.8.86
  - cuda-nsight=12.0.78
  - cuda-nsight-compute=12.0.0
  - cuda-nvcc=11.7.99
  - cuda-nvdisasm=12.0.76
  - cuda-nvml-dev=11.7.91
  - cuda-nvprof=12.0.90
  - cuda-nvprune=11.7.91
  - cuda-nvrtc=11.7.99
  - cuda-nvrtc-dev=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-nvvp=12.0.90
  - cuda-runtime=11.7.1
  - cuda-sanitizer-api=12.0.90
  - cuda-toolkit=11.7.1
  - cuda-tools=11.7.1
  - cuda-visual-tools=11.7.1
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask-core=2022.7.0
  - dbus=1.13.18
  - dill=0.3.6
  - et_xmlfile=1.1.0
  - expat=2.2.10
  - ffmpeg=4.3
  - fftw=3.3.9
  - flit-core=3.6.0
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - fsspec=2022.11.0
  - gds-tools=1.5.0.59
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=3.4
  - imagecodecs=2021.8.26
  - imageio=2.19.3
  - intel-openmp=2021.4.0
  - joblib=1.1.1
  - jpeg=9e
  - jxrlib=1.1
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.19.3
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libaec=1.0.4
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=10.0.1
  - libcublas=11.10.3.66
  - libcublas-dev=11.10.3.66
  - libcufft=10.7.2.124
  - libcufft-dev=10.7.2.124
  - libcufile=1.5.0.59
  - libcufile-dev=1.5.0.59
  - libcurand=10.3.1.50
  - libcurand-dev=10.3.1.50
  - libcurl=7.87.0
  - libcusolver=11.4.0.1
  - libcusolver-dev=11.4.0.1
  - libcusparse=11.7.4.91
  - libcusparse-dev=11.7.4.91
  - libdeflate=1.8
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libllvm10=10.0.1
  - libnghttp2=1.46.0
  - libnpp=11.7.4.75
  - libnpp-dev=11.7.4.75
  - libnvjpeg=11.8.0.2
  - libnvjpeg-dev=11.8.0.2
  - libpng=1.6.37
  - libpq=12.9
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.3
  - libxml2=2.9.14
  - libxslt=1.1.35
  - libzopfli=1.0.3
  - locket=1.0.0
  - lz4-c=1.9.4
  - matplotlib=3.6.2
  - matplotlib-base=3.6.2
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=2.8.4
  - nsight-compute=2022.4.0.15
  - nspr=4.33
  - nss=3.74
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openpyxl=3.0.10
  - openssl=1.1.1s
  - packaging=23.0
  - partd=1.2.0
  - pcre=8.45
  - pillow=9.3.0
  - pip=22.3.1
  - ply=3.11
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pysocks=1.7.1
  - python=3.10.9
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytorch=1.13.1
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - pywavelets=1.4.1
  - pyyaml=6.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - readline=8.2
  - requests=2.28.1
  - scikit-image=0.19.3
  - scikit-learn=1.2.0
  - scipy=1.9.3
  - setuptools=65.6.3
  - sip=6.6.2
  - six=1.16.0
  - snappy=1.1.9
  - sqlite=3.40.1
  - threadpoolctl=2.2.0
  - tifffile=2021.7.2
  - tk=8.6.12
  - toml=0.10.2
  - toolz=0.12.0
  - torchaudio=0.13.1
  - torchvision=0.14.1
  - tornado=6.1
  - typing_extensions=4.4.0
  - tzdata=2022g
  - urllib3=1.26.14
  - wheel=0.37.1
  - xz=5.2.10
  - yaml=0.2.5
  - zfp=0.5.5
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - addcopyfighandler
      - pyqt5-sip
      - python-graphviz
      - torchviz
